### ISSUE TITLE
Please add Melbourne Makerspace 

### ISSUE THREAD

**Issue by ramgarden** [fixme-lausanne/OpenSpaceDirectory#36]
http://spaceapi.net/new/space/melbourne_makerspace/status/json

That's what we have currently.

**Comment by rorist** [comment]
Hello,

You can do a Pull Request with the URL you want changed.
AFAIK spaceapi.net is not maintained anymore, MyHackerspace android app is using spaceapi.fixme.ch, which is now part of the effort to bring back the SpaceAPI, over there https://spacedirectory.org/

Cheers
